### ISSUE TITLE
Download ALL data fields instead of just basic

### ISSUE THREAD

**Issue by JojoReikun** [AtlasOfLivingAustralia/galah-python#206]
Hey acbuyan,

I have another question, I haven't managed to figure out yet myself, maybe you're able to help me: 
For a project I would need to download all available fields of a specific data resource.
The resource has ~1500 entries, the massive download would only be once, then afterwards I want to only download the newly added entries afterwards in a weekly manner, hence maybe 10-20, but I would always need all fields. 

Is there a way to not just download "basic", or "media" fields as pre-defined defaults?

I have generated a list of all available fields (611) using this line:
`esri_fields_list = list(df_fields["id"])`
and then passed this list in the atlas_occurrences query:
`galah.atlas_occurrences(taxa="Phascolarctos cinereus", filters="dataResourceUid==dr19064", fields=esri_fields_list, verbose=True)`

**The error occurring:**
URL for querying:

https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&qualityProfile=ALA&fields=abcdTypeStatus%2CacceptedNameUsage%2CacceptedNameUsageID%2CaccessRights%2CassertionUserId%2Cassertions%2CassociatedMedia%2CassociatedOccurrences%2CassociatedOrganisms%2CassociatedReferences%2CassociatedSequences%2CassociatedTaxa%2CbasisOfRecord%2Cbed%2Cbehavior%2CbibliographicCitation%2Cbiome%2CcatalogNumber%2Cclass%2CclassID%2CclassKey%2CcollectionCode%2CcollectionID%2CcollectionName%2CcollectionUid%2Ccommon_name_and_lsid%2CcontentTypes%2Ccontinent%2CcoordinatePrecision%2CcoordinateUncertaintyInMeters%2Ccountry%2CcountryCode%2CcountryConservation%2CcountryInvasive%2Ccounty%2CdataGeneralizations%2CdataHubName%2CdataHubUid%2CdataProviderName%2CdataProviderUid%2CdataResourceName%2CdataResourceUid%2CdatasetID%2CdatasetName%2CdateIdentified%2CdatePrecision%2Cday%2Cdecade%2CdecimalLatitude%2CdecimalLongitude%2CdefaultValuesUsed%2CdepthAccuracy%2Cdisposition%2CdistanceFromExpertDistribution%2CduplicateJustification%2CduplicateStatus%2CduplicateType%2CdynamicProperties%2CearliestAgeOrLowestStage%2CearliestEonOrLowestEonothem%2CearliestEpochOrLowestSeries%2CearliestEraOrLowestErathem%2CearliestGeochronologicalEra%2CearliestPeriodOrLowestSystem%2Ceasting%2CelevationAccuracy%2CendDayOfYear%2CestablishmentMeans%2CeventDate%2CeventDateEnd%2CeventID%2CeventRemarks%2CeventTime%2Cfamily%2CfamilyID%2CfieldNotes%2CfieldNumber%2CfirstLoadedDate%2CfootprintSRS%2CfootprintSpatialFit%2CfootprintWKT%2Cformation%2CfromLithostratigraphicUnit%2CgeneralisationInMetres%2CgeneralisationToApplyInMetres%2Cgenus%2CgenusID%2CgeodeticDatum%2Cgeohash%2CgeologicalContextID%2CgeoreferenceProtocol%2CgeoreferenceRemarks%2CgeoreferenceSources%2CgeoreferenceVerificationStatus%2CgeoreferencedBy%2CgeoreferencedDate%2CgeospatialIssues%2Cgroup%2Chabitat%2ChasUserAssertions%2ChigherClassification%2ChigherGeography%2ChigherGeographyID%2ChighestBiostratigraphicZone%2Cid%2CidentificationID%2CidentificationQualifier%2CidentificationReferences%2CidentificationRemarks%2CidentificationVerificationStatus%2CidentifiedBy%2CidentifiedByID%2CidentifierRole%2CimageID%2CimageIDs%2CinCollection%2CinDataset%2CinDescribedPlace%2CindividualCount%2CinformationWithheld%2CinfraspecificEpithet%2CinstitutionCode%2CinstitutionID%2CinstitutionName%2CinstitutionUid%2CisDuplicateOf%2CisInCluster%2CisRepresentativeOf%2Cisland%2CislandGroup%2Ckingdom%2CkingdomID%2Clabel%2Clanguage%2ClastAssertionDate%2ClastLoadDate%2ClastProcessedDate%2Clat_long%2ClatestAgeOrHighestStage%2ClatestEonOrHighestEonothem%2ClatestEpochOrHighestSeries%2ClatestEraOrHighestErathem%2ClatestGeochronologicalEra%2ClatestPeriodOrHighestSystem%2Clft%2Clicense%2ClifeStage%2ClifeStageLineage%2ClithostratigraphicTerms%2CloanDestination%2CloanIdentifier%2Clocality%2Clocation%2ClocationAccordingTo%2ClocationID%2ClocationRemarks%2ClowestBiostratigraphicZone%2CmachineTags%2CmatchType%2CmaterialSampleID%2CmaximumDepthInMeters%2CmaximumDistanceAboveSurfaceInMeters%2CmaximumElevationInMeters%2CmeasurementAccuracy%2CmeasurementDeterminedBy%2CmeasurementDeterminedDate%2CmeasurementID%2CmeasurementMethod%2CmeasurementRemarks%2CmeasurementType%2CmeasurementUnit%2CmeasurementValue%2Cmember%2CminimumDepthInMeters%2CminimumDistanceAboveSurfaceInMeters%2CminimumElevationInMeters%2Cmodified%2Cmonth%2Cmultimedia%2CmultimediaLicense%2Cmunicipality%2CnameAccordingTo%2CnameAccordingToID%2CnamePublishedIn%2CnamePublishedInID%2CnamePublishedInYear%2CnameType%2Cnames_and_lsid%2Cnick%2CnomenclaturalCode%2CnomenclaturalStatus%2Cnorthing%2Cnull%2CnumIdentificationAgreements%2CnumIdentificationDisagreements%2CoccurrenceDetails%2CoccurrenceID%2CoccurrenceRemarks%2CoccurrenceStatus%2CoccurrenceYear%2Corder%2CorderID%2CorganismID%2CorganismName%2CorganismQuantity%2CorganismQuantityType%2CorganismRemarks%2CorganismScope%2CoriginalNameUsage%2CoriginalNameUsageID%2CotherCatalogNumbers%2CoutlierLayer%2CoutlierLayerCount%2CownerInstitutionCode%2CpackedQuad%2CparentEventID%2CparentNameUsage%2CparentNameUsageID%2Cphylum%2CphylumID%2Cpoint-0.0001%2Cpoint-0.001%2Cpoint-0.01%2Cpoint-0.02%2Cpoint-0.1%2Cpoint-1%2CpointRadiusSpatialFit%2CpositioningDevice%2CpositioningMethod%2Cpreparations%2CpreviousIdentifications%2Cprovenance%2Cquad%2Craw_altered%2Craw_associatedOccurrences%2Craw_audience%2Craw_basisOfRecord%2Craw_biome%2Craw_class%2Craw_classID%2Craw_collectionName%2Craw_collectionUid%2Craw_connectionParameters%2Craw_conservationStatuses%2Craw_continent%2Craw_contributor%2Craw_coordinatePrecision%2Craw_coordinateUncertaintyInMeters%2Craw_country%2Craw_countryCode%2Craw_created%2Craw_creator%2Craw_dataGeneralizations%2Craw_dataProviderName%2Craw_dataProviderUid%2Craw_dataResourceName%2Craw_dataResourceUid%2Craw_datasetID%2Craw_datasetName%2Craw_datasetTitle%2Craw_dateIdentified%2Craw_datePrecision%2Craw_day%2Craw_decimalLatitude%2Craw_decimalLongitude%2Craw_degreeOfEstablishment%2Craw_depth%2Craw_depthAccuracy%2Craw_description%2Craw_dynamicProperties%2Craw_elevation%2Craw_elevationAccuracy%2Craw_endDayOfYear%2Craw_establishmentMeans%2Craw_eventDate%2Craw_family%2Craw_familyID%2Craw_footprintWKT%2Craw_format%2Craw_generalisationInMetres%2Craw_generalisationToApplyInMetres%2Craw_genus%2Craw_genusID%2Craw_geodeticDatum%2Craw_georeferencedDate%2Craw_hasCoordinate%2Craw_identifiedBy%2Craw_identifiedByIds%2Craw_identifier%2Craw_individualCount%2Craw_informationWithheld%2Craw_installationKey%2Craw_institutionName%2Craw_institutionUid%2Craw_invasiveStatuses%2Craw_isClustered%2Craw_isSensitive%2Craw_issues%2Craw_kingdom%2Craw_kingdomID%2Craw_lastCrawled%2Craw_lastLoadDate%2Craw_lastProcessedDate%2Craw_lft%2Craw_license%2Craw_licenseType%2Craw_licenseVersion%2Craw_lifeStage%2Craw_lifeStageLineage%2Craw_locality%2Craw_machineTags%2Craw_matchType%2Craw_maximumDepthInMeters%2Craw_maximumDistanceAboveSurfaceInMeters%2Craw_maximumElevationInMeters%2Craw_minimumDepthInMeters%2Craw_minimumDistanceAboveSurfaceInMeters%2Craw_minimumElevationInMeters%2Craw_modified%2Craw_month%2Craw_nameType%2Craw_networkKeys%2Craw_occurrenceStatus%2Craw_order%2Craw_orderID%2Craw_organismQuantity%2Craw_organismQuantityType%2Craw_original%2Craw_otherCatalogNumbers%2Craw_phylum%2Craw_phylumID%2Craw_preparations%2Craw_provenance%2Craw_publisher%2Craw_publisherTitle%2Craw_publishingCountry%2Craw_publishingOrganizationKey%2Craw_recordedBy%2Craw_recordedByIds%2Craw_references%2Craw_relativeOrganismQuantity%2Craw_repatriated%2Craw_rgt%2Craw_rightsHolder%2Craw_sampleSizeUnit%2Craw_sampleSizeValue%2Craw_samplingProtocol%2Craw_scientificName%2Craw_scientificNameAuthorship%2Craw_sensitive%2Craw_sex%2Craw_source%2Craw_species%2Craw_speciesGroup%2Craw_speciesID%2Craw_speciesListID%2Craw_speciesSubgroup%2Craw_startDayOfYear%2Craw_stateConservation%2Craw_stateProvince%2Craw_taxonConceptID%2Craw_taxonRank%2Craw_taxonRankID%2Craw_title%2Craw_type%2Craw_typeStatus%2Craw_typifiedName%2Craw_verbatimCoordinates%2Craw_vernacularName%2Craw_waterBody%2Craw_year%2CrecordNumber%2CrecordedBy%2CrecordedByID%2Creferences%2CrelatedResourceID%2CrelationshipAccordingTo%2CrelationshipEstablishedDate%2CrelationshipOfResource%2CrelationshipRemarks%2CrelativeOrganismQuantity%2CreproductiveCondition%2CresourceID%2CresourceRelationshipID%2Crgt%2Crights%2CrightsHolder%2CsampleSizeUnit%2CsampleSizeValue%2CsamplingEffort%2CsamplingProtocol%2CscientificName%2CscientificNameAuthorship%2CscientificNameID%2CsecondaryCollectors%2Csensitive%2Csex%2CsoundIDs%2Csource%2CspatiallyValid%2Cspecies%2CspeciesGroup%2CspeciesID%2CspeciesListUid%2CspeciesSubgroup%2CspecificEpithet%2CstartDayOfYear%2CstateConservation%2CstateInvasive%2CstateProvince%2Csubfamily%2Csubgenus%2Csubspecies%2CsubspeciesID%2Csuperfamily%2CtaxonConceptID%2CtaxonID%2CtaxonRank%2CtaxonRankID%2CtaxonRemarks%2CtaxonomicIssues%2CtaxonomicStatus%2Ctext%2Ctext_datasetName%2Ctext_eventID%2Ctext_fieldNumber%2Ctext_identifiedBy%2Ctext_parentEventID%2Ctext_recordedBy%2CtoTaxon%2Ctype%2CtypeStatus%2CtypifiedName%2CuserAssertions%2CuserId%2CuserVerified%2CverbatimCoordinateSystem%2CverbatimCoordinates%2CverbatimDepth%2CverbatimElevation%2CverbatimEventDate%2CverbatimLatitude%2CverbatimLocality%2CverbatimLongitude%2CverbatimSRS%2CverbatimTaxonRank%2CvernacularName%2CvideoIDs%2CwaterBody%2Cyear%2Czone%2Cel10996%2Ccl620%2Ccl10900%2Cel10995%2Cel10993%2Cel10990%2Cel875%2Ccl936%2Ccl964%2Cel799%2Ccl906%2Ccl2125%2Cel10984%2Cel10982%2Cel798%2Ccl10923%2Cel797%2Cel796%2Cel795%2Cel792%2Cel784%2Cel789%2Cel783%2Ccl23%2Cel781%2Ccl917%2Ccl907%2Ccl908%2Ccl910%2Ccl911%2Ccl965%2Ccl10933%2Ccl10902%2Ccl10935%2Ccl10903%2Ccl3%2Ccl938%2Ccl11033%2Ccl10936%2Ccl11032%2Cel674%2Ccl617%2Ccl961%2Cel790%2Ccl20%2Ccl918%2Ccl963%2Cel862%2Cel882%2Cel870%2Cel892%2Cel865%2Cel867%2Cel883%2Cel891%2Cel894%2Cel887%2Cel881%2Cel888%2Cel863%2Cel878%2Cel889%2Cel886%2Ccl2116%2Cel893%2Cel876%2Cel890%2Cel874%2Ccl2109%2Ccl932%2Ccl2117%2Ccl2115%2Ccl941%2Ccl962%2Ccl2013%2Ccl2050%2Ccl2049%2Ccl2048%2Ccl2015%2Ccl2010%2Ccl2009%2Ccl2012%2Ccl937%2Ccl1059%2Ccl1058%2Ccl1049%2Ccl1048%2Ccl940%2Ccl990%2Ccl966%2Ccl939%2Ccl901%2Ccl935%2Ccl913%2Ccl21%2Ccl927%2Ccl929%2Ccl10912%2Ccl22%2Ccl1062%2Ccl1067%2Ccl1064%2Ccl1054%2Ccl1066%2Ccl1063%2Ccl1070%2Ccl1069%2Ccl1068%2Ccl10921%2Ccl900%2Ccl10922%2Ccl10929%2Ccl10925%2Ccl10927%2Ccl10928%2Ccl10934%2Ccl10942%2Ccl10941%2Ccl10943%2Ccl10930%2Ccl916%2Ccl959%2Ccl10946%2Ccl10955%2Cel879%2Cel872%2Cel866%2Ccl10945%2Ccl10944%2Ccl1065%2Ccl2124%2Ccl960%2Cel10981%2Cel10980%2Cel10994%2Cel10992%2Cel10991%2Cel10983%2Cel10978%2Cel10989%2Cel10986%2Cel10979%2Cel10987%2Cel10988%2Cel10985%2Cel787%2Cel786%2Cel785%2Cel782%2Cel794%2Cel791%2Cel793%2Cel788%2Ccl10000%2Cmultimedia%2CmultimediaLicence%2Cimages%2Cvideos%2Csounds%2Cqid&&fq=%28lsid%3Ahttps%3A//biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6%29%20AND%20%28%28dataResourceUid%3A%22dr19064%22%29%29&qa=none&

Traceback (most recent call last):
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 11, in <module>
    main()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 7, in main
    download_ala_data()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\operations\galah_data_download.py", line 97, in download_ala_data
    galah_tests()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\operations\galah_data_download.py", line 46, in galah_tests
    redlands_occurrences = galah.atlas_occurrences(taxa="Phascolarctos cinereus", filters="dataResourceUid==dr19064", use_data_profile=True, fields=esri_fields_list, verbose=True)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\galah\atlas_occurrences.py", line 243, in atlas_occurrences
    if response.json()['status'] == "skipped":
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by acbuyan** [comment]
Hi JojoReikun,

thanks for writing again!  In the future, if it is helpful, I can include an option where you type in "all" and it includes all fields by default, if that would be helpful.  I'll look into this and get back to you today about a workaround until the next release.

**Comment by acbuyan** [comment]
Hi @JojoReikun,

I've figured out a workaround.  It's not ideal, but it's something, and I can push the changes this afternoon if you want to work off the development version (cannot promise it will be amazing!)

if you prefer to work off the released version, make sure fields are

`['basisOfRecord', 'catalogNumber', 'cl1048', 'cl21', 'cl959', 'class', 'collectionCode', 'collectionName', 'collectionUid', 'coordinatePrecision', 'coordinateUncertaintyInMeters', 'country', 'dataGeneralizations', 'dataResourceUid', 'day', 'dcterms:license', 'decimalLatitude', 'decimalLongitude', 'eventDate', 'family', 'genus', 'individualCount', 'informationWithheld', 'institutionCode', 'institutionName', 'institutionUid', 'kingdom', 'locality', 'maximumDepthInMeters', 'maximumElevationInMeters', 'minimumDepthInMeters', 'minimumElevationInMeters', 'month', 'occurrenceStatus', 'order', 'phylum', 'preparations', 'raw_sex', 'raw_vernacularName', 'recordID', 'recordedBy', 'scientificName', 'spatiallyValid', 'species', 'stateProvince', 'subspecies', 'taxonConceptID', 'taxonRank', 'verbatimBasisOfRecord', 'verbatimCoordinateSystem', 'verbatimLatitude', 'verbatimLongitude', 'verbatimScientificName', 'vernacularName', 'year']`

this is the default that the ALA returns if you don't specify fields.

in the new version, if you specify "all" as fields, it will automatically return all of these.

**Comment by JojoReikun** [comment]
Hey @acbuyan,

thanks so much for providing this info. Having the option to use "all" in future would be great! For now this list of field names works perfectly. Thank you!!
Love your work!

Regards, 
jojo

**Comment by JojoReikun** [comment]
Hey @acbuyan,

I might continue in this thread to ask another question. I have also raised this with the support team from ALA, as it's just a question about field name mappings when data is transferred from BioCollect to ALA.
I can now successfully download the data and I have a selection of fields, which we need. However some specific info, columns like:
"Describe any injuries", "Young present?", "Radiotracking", "Collar", etc., which are present on BioCollect, I could not find in any of the fields on ALA. I manually went through the complete list here: https://biocache.ala.org.au/fields?filter=&offset=590&max=10&sort=name&order=ASC, and downloaded all potential matches, and I also searched for strings that may be included in the field name. 
In the hope that all data is transferred from BioCollect to ALA, do you happen to know the field mapping?
I have a csv file which contains the required fields I am still looking for and mostly empty or not matching ALA fields, that may correspond to them.
[ALA_fieldname_detective.csv](https://github.com/AtlasOfLivingAustralia/galah-python/files/14579397/ALA_fieldname_detective.csv)

Not sure if this is something you know!
Feel free to close this if not :)

Thanks,
Jojo
