### ISSUE TITLE
atlas_media() MissingSchema error when collect=True

### ISSUE THREAD

**Issue by JojoReikun** [AtlasOfLivingAustralia/galah-python#210]
Hey @acbuyan,

I have recently progressed with the script I'm writing for automatic data download from an ALA resource stemming from a citizen science project.
I need to download the media as well as the occurrences data, but testing the download since the last download, the atlas_media() function came up with an error of an internal module:

A few images run successfully [...], but then the error occurs, see console output below.
It doesn't seem to go through your check in atlas_media if collect==True where you test if image was retrieved?

Consule output:

`running Koala Watch Dashboard Script...
downloading RCC data since last download.
last_download_date:  2023-07-10T14:23:19Z
['dataResourceUid==dr19064', 'eventDate>=2023-07-10T14:23:19Z']
koala_watch_occurrences_count:     totalRecords
0            73
URL for querying:

https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=jojo.schultz%40outlook.de&dwcHeaders=True&reasonTypeId=4&emailNotify=false&disableAllQualityfilters=true&fields=basisOfRecord%2CcatalogNumber%2Ccl1048%2Ccl21%2Ccl959%2Cclass%2CcollectionCode%2CcollectionName%2CcollectionUid%2CcoordinatePrecision%2CcoordinateUncertaintyInMeters%2Ccountry%2CdataGeneralizations%2CdataResourceUid%2Cday%2Cdcterms:license%2CdecimalLatitude%2CdecimalLongitude%2CeventDate%2Cfamily%2Cgenus%2CindividualCount%2CinformationWithheld%2CinstitutionCode%2CinstitutionName%2CinstitutionUid%2Ckingdom%2Clocality%2CmaximumDepthInMeters%2CmaximumElevationInMeters%2CminimumDepthInMeters%2CminimumElevationInMeters%2Cmonth%2CoccurrenceStatus%2Corder%2Cphylum%2Cpreparations%2Craw_sex%2Craw_vernacularName%2CrecordID%2CrecordedBy%2CscientificName%2CspatiallyValid%2Cspecies%2CstateProvince%2Csubspecies%2CtaxonConceptID%2CtaxonRank%2CverbatimBasisOfRecord%2CverbatimCoordinateSystem%2CverbatimLatitude%2CverbatimLongitude%2CverbatimScientificName%2CvernacularName%2Cyear&&fq=%28lsid%3Ahttps%3A//biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6%29%20AND%20%28%28dataResourceUid%3A%22dr19064%22%29%20AND%20%28eventDate%3A%5B2023-07-10T14:23:19Z%20TO%20%2A%5d%29%29&qa=none&

Data for download:

https://biocache.ala.org.au/biocache-download/7d58aab5-1e0f-384d-ba9a-f632fb210b51/1691384065893/data.zip

size of dataframe:  (73, 53)
Do you want to download the media files (photos etc.)? (y/n): y

[...]

URL for querying:

https://images.ala.org.au/ws/image/a6177554-e6d0-43c7-8ab9-b279aadec230

Traceback (most recent call last):
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 14, in <module>
    main()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\__main__.py", line 9, in main
    download_ala_data()
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\operations\galah_data_download.py", line 304, in download_ala_data
    subsequent_download_ala_data(collect_bool=False)
  File "D:\Jojo\DDC\KoalaWatchDashboard\KoalaDashboardScript\KoalaWatch\operations\galah_data_download.py", line 246, in subsequent_download_ala_data
    df_occurrences_media = galah.atlas_media(taxa="Phascolarctos cinereus", filters=filter_date_new,
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\galah\atlas_media.py", line 230, in atlas_media
    response = requests.get(image,stream=True)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\JojoS\Miniconda3\envs\KoalaDashboardScript\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '0_IMG_0437.JPG': No scheme supplied. Perhaps you meant https://0_IMG_0437.JPG?

Process finished with exit code 1
`

Do you know about this issue? Might it be because image naming could differ in a citizen science project?
I'm not sure if this error is something you can fix, or might result from the ALA server itself.
Any pointer is greatly appreciated.

Kind regards,
Jojo

**Comment by acbuyan** [comment]
HI @JojoReikun, thanks as always for your feedback!  So, could you provide the code you are using to collect the media from `atlas_media()`?

**Comment by JojoReikun** [comment]
Hey @acbuyan,

That would have been helpful hey, here it is:
`filter_date_new = ["dataResourceUid==dr19064", "eventDate>=" + str(last_download_date)]`
`df_occurrences_media = galah.atlas_media(taxa="Phascolarctos cinereus", filters=filter_date_new,
                                             verbose=True, collect=collect_bool, path="redlands_media")`

**Comment by acbuyan** [comment]
and one more question: what is the download date?

**Comment by JojoReikun** [comment]
The last download date I used that threw the error was the 10th of July 2023

**Comment by acbuyan** [comment]
hm....one other question (because I'm not sure why this is happening, to be honest): does your download script rename anything? Or does it just call galah?

**Comment by JojoReikun** [comment]
it calls the function pretty much immediately. 
I was wondering whether it is a problem related to the file naming of the specific photo?
Given that about 20 or so photos prior to the error the url returned from verbose works without a problem, however the media folder remains completely empty. 
Would there be an option to skip these unsuccessful url requests if we can't find the issue? :)
I'm wondering why it wouldn't be picked up from your check loop.

I'll try debug this problem myself further too. Should I find anything, I'll let you know.

Cheers,
Jojo

**Comment by acbuyan** [comment]
this is a silly question, but did you provide your email before you run the query?

**Comment by JojoReikun** [comment]
yup, I use galah_config() defining atlas and email as the first thing :)

I have tried to avoid the buggy photo by manually selecting download windows of the eventDate and other photos come up too.
I know that the rightHolders of these photos submit many data Points so it seems to really be a few occasions that this is happening. 
The photos that come up with the missing Scheme error lay about 5-6 days appart...

**Comment by acbuyan** [comment]
ok, this is good information to know.  I'll look into it, and it should be fixed in the next release of `galah-python`.  I'm sorry that I'm not sure what to tell you in the meantime.  I'll look into it in the meantime

**Comment by JojoReikun** [comment]
thank you!
I can't explain this either :)
Let me know if you need any further information.

**Comment by acbuyan** [comment]
Hi again Jojo,

I believe the issue of atlas_media not downloading things correctly has been fixed, but please feel free to message me if it has not :)
